FROM pytorch/pytorch:2.12.1-cuda12.6-cudnn9-devel

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV UV_BREAK_SYSTEM_PACKAGES=true

WORKDIR /workspace

COPY . /workspace

RUN set -eux && apt-get update && \
    apt-get install -y --no-install-recommends vim openssh-client openssh-server systemd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /run/sshd && \
    chmod 0755 /run/sshd && \
    uv pip install --system -e ".[dev,metrics,deepspeed]" && \
    pip install jupyter_core notebook jupyterhub jupyterlab && \
    llamafactory-cli version && \
    pip cache purge && \
    uv cache clean
