ARG CUDA_VERSION=13.0.2
ARG PYTHON_VERSION=3.12
ARG UBUNTU_VERSION=22.04

ARG FINAL_BASE_IMAGE=nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu${UBUNTU_VERSION}

FROM ${FINAL_BASE_IMAGE}

RUN set -eux && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    ccache \
    cmake \
    curl \
    git \
    vim \
    libjpeg-dev \
    libpng-dev \
    python3 \
    python3-pip \
    python-is-python3 \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN set -eux && \
    ls -al && \
    pip install uv && \
    uv pip install --system -e ".[dev,metrics,deepspeed]" && \
    llamafactory-cli version && \
    pip cache purge && \
    uv cache clean
