# FROM pytorch/pytorch:2.12.1-cuda12.6-cudnn9-devel
FROM nvidia/cuda:12.6.3-cudnn-devel-ubuntu20.04

# Use Bash instead of default /bin/sh
SHELL ["/bin/bash", "-c"]

# Set the working directory
WORKDIR /app

# Copy the application into the image
COPY . /app

RUN set -eux && \
    ls -al && \
    pip install uv && \
    uv pip install -e ".[dev,metrics,deepspeed]" && \
    llamafactory-cli version
